/**
 * Embed logo files (logo-hp.png + logo-hp.ico) thành base64 + SHA-256 hash
 * vào module src/embedded-logos.js.
 *
 * Mục đích: bảo vệ logo sau khi pack vào .exe — không có file riêng để user
 * có thể thay thế. Logo nằm trong app.asar dưới dạng compiled JS.
 *
 * Run: node tools/embed-logos.js
 *      (hoặc npm run embed-logos)
 *
 * Sau mỗi lần đổi logo (image source) → re-run script này → commit + build.
 */
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const ROOT = path.join(__dirname, '..');
const PNG_PATH = path.join(ROOT, 'logo-hp.png');
const ICO_PATH = path.join(ROOT, 'logo-hp.ico');
const OUT_PATH = path.join(ROOT, 'src', 'embedded-logos.js');

function readBase64(p) {
  if (!fs.existsSync(p)) {
    console.error(`Missing source: ${p}`);
    process.exit(1);
  }
  const buf = fs.readFileSync(p);
  return {
    base64: buf.toString('base64'),
    hash: crypto.createHash('sha256').update(buf).digest('hex'),
    size: buf.length,
  };
}

const png = readBase64(PNG_PATH);
const ico = readBase64(ICO_PATH);

const out = `// AUTO-GENERATED by tools/embed-logos.js — DO NOT EDIT MANUALLY.
// Logos embedded as base64 với SHA-256 hash để verify integrity at runtime.
// Sau khi pack vào app.asar:
//   - Không còn logo-hp.png / logo-hp.ico riêng trong resources/.
//   - User không thể thay logo bằng cách swap file (vì không tồn tại file).
//   - Hash check ở main.js sẽ phát hiện nếu ai đó modify base64 string trong JS.
'use strict';

const LOGO_PNG_BASE64 = '${png.base64}';
const LOGO_PNG_HASH = '${png.hash}';
const LOGO_PNG_DATA_URL = 'data:image/png;base64,' + LOGO_PNG_BASE64;

const LOGO_ICO_BASE64 = '${ico.base64}';
const LOGO_ICO_HASH = '${ico.hash}';
const LOGO_ICO_DATA_URL = 'data:image/x-icon;base64,' + LOGO_ICO_BASE64;

module.exports = {
  LOGO_PNG_BASE64, LOGO_PNG_HASH, LOGO_PNG_DATA_URL,
  LOGO_ICO_BASE64, LOGO_ICO_HASH, LOGO_ICO_DATA_URL,
};
`;

fs.writeFileSync(OUT_PATH, out, 'utf8');

console.log('═══════════════════════════════════════════════════');
console.log('  Embedded logos generated → src/embedded-logos.js');
console.log('═══════════════════════════════════════════════════');
console.log(`  PNG: ${png.size} bytes → base64 ${png.base64.length} chars`);
console.log(`  PNG hash: ${png.hash}`);
console.log(`  ICO: ${ico.size} bytes → base64 ${ico.base64.length} chars`);
console.log(`  ICO hash: ${ico.hash}`);
console.log(`  Output total: ${(out.length / 1024).toFixed(1)} KB`);
console.log('═══════════════════════════════════════════════════');
